version: '3.3'

services:
  db:
    image: mysql:5.6
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: database
      MYSQL_USER: database_user
      MYSQL_PASSWORD: 12345678
    volumes:
      - projectsqldata:/var/lib/mysql
  php:
    build: ./docker/php
    links:
      - db
    ports:
      - "9000:9000"
    volumes:
      - ./project:/var/www/html

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./project:/var/www/html
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

volumes:
  projectsqldata:
    driver: "local"